// categoriesData static data
export const categoriesData = [
  { title: "Electronics" },
  { title: "Clothing" },
  { title: "Home & Kitchen" },
  { title: "Books" },
  { title: "Sports & Outdoors" },
  // Add more categories if needed
];

// productsData static data
export const productsData = [
  {
    _id: "1",
    name: "Smartphone",
    description: "High-end smartphone with advanced features.",
    category: "Electronics",
    tags: ["Smartphone", "Mobile", "Gadgets"],
  },
  {
    _id: "2",
    name: "T-shirt",
    description: "Casual cotton t-shirt for everyday wear.",
    category: "Clothing",
    tags: ["T-shirt", "Clothing", "Fashion"],
  },
  {
    _id: "3",
    name: "Coffee Maker",
    description: "Automatic coffee maker for brewing delicious coffee.",
    category: "Home & Kitchen",
    tags: ["Coffee Maker", "Home Appliances", "Kitchen Appliances"],
  },
  {
    _id: "4",
    name: "Novel",
    description: "Bestselling novel by a renowned author.",
    category: "Books",
    tags: ["Novel", "Book", "Literature"],
  },
  {
    _id: "5",
    name: "Yoga Mat",
    description: "High-quality yoga mat for practicing yoga and meditation.",
    category: "Sports & Outdoors",
    tags: ["Yoga Mat", "Fitness", "Exercise"],
  },
  {
    _id: "6",
    name: "Laptop",
    description: "Powerful laptop for work and entertainment.",
    category: "Electronics",
    tags: ["Laptop", "Computer", "Technology"],
  },
  {
    _id: "7",
    name: "Dress Shirt",
    description: "Formal dress shirt for men.",
    category: "Clothing",
    tags: ["Shirt", "Clothing", "Formal"],
  },
  {
    _id: "8",
    name: "Blender",
    description: "High-speed blender for making smoothies and sauces.",
    category: "Home & Kitchen",
    tags: ["Blender", "Appliances", "Kitchen"],
  },
  {
    _id: "9",
    name: "Cookbook",
    description: "Collection of delicious recipes for every occasion.",
    category: "Books",
    tags: ["Cookbook", "Recipes", "Cooking"],
  },
  {
    _id: "10",
    name: "Tennis Racket",
    description: "Professional tennis racket for serious players.",
    category: "Sports & Outdoors",
    tags: ["Tennis Racket", "Sports", "Tennis"],
  },
  {
    _id: "11",
    name: "Headphones",
    description: "High-quality headphones for immersive audio experience.",
    category: "Electronics",
    tags: ["Headphones", "Audio", "Gadgets"],
  },
  {
    _id: "12",
    name: "Jeans",
    description: "Classic denim jeans for casual wear.",
    category: "Clothing",
    tags: ["Jeans", "Clothing", "Fashion"],
  },
  {
    _id: "13",
    name: "Toaster",
    description: "Two-slice toaster for toasting bread and bagels.",
    category: "Home & Kitchen",
    tags: ["Toaster", "Appliances", "Kitchen"],
  },
  {
    _id: "14",
    name: "Art Book",
    description: "Beautifully illustrated art book featuring famous artworks.",
    category: "Books",
    tags: ["Art Book", "Art", "Culture"],
  },
  {
    _id: "15",
    name: "Running Shoes",
    description: "Lightweight and comfortable running shoes for athletes.",
    category: "Sports & Outdoors",
    tags: ["Running Shoes", "Sports", "Running"],
  },
  {
    _id: "16",
    name: "Desktop Computer",
    description:
      "High-performance desktop computer for gaming and productivity.",
    category: "Electronics",
    tags: ["Desktop Computer", "Computer", "Technology"],
  },
  {
    _id: "17",
    name: "Polo Shirt",
    description: "Casual polo shirt for men.",
    category: "Clothing",
    tags: ["Polo Shirt", "Clothing", "Casual"],
  },
  {
    _id: "18",
    name: "Microwave Oven",
    description: "Compact microwave oven for heating and cooking food.",
    category: "Home & Kitchen",
    tags: ["Microwave Oven", "Appliances", "Kitchen"],
  },
  {
    _id: "19",
    name: "Travel Guide",
    description:
      "Comprehensive travel guide for exploring destinations around the world.",
    category: "Books",
    tags: ["Travel Guide", "Travel", "Tourism"],
  },
  {
    _id: "20",
    name: "Basketball",
    description: "Official-size basketball for indoor and outdoor play.",
    category: "Sports & Outdoors",
    tags: ["Basketball", "Sports", "Basketball"],
  },
  {
    _id: "21",
    name: "Smart Watch",
    description:
      "Advanced smartwatch with health and fitness tracking features.",
    category: "Electronics",
    tags: ["Smart Watch", "Wearable", "Gadgets"],
  },
  {
    _id: "22",
    name: "Hoodie",
    description: "Comfortable hoodie for casual and outdoor wear.",
    category: "Clothing",
    tags: ["Hoodie", "Clothing", "Fashion"],
  },
  {
    _id: "23",
    name: "Air Fryer",
    description: "Oil-less air fryer for healthier frying and cooking.",
    category: "Home & Kitchen",
    tags: ["Air Fryer", "Appliances", "Kitchen"],
  },
  {
    _id: "24",
    name: "Self-Help Book",
    description:
      "Motivational self-help book for personal growth and development.",
    category: "Books",
    tags: ["Self-Help Book", "Motivation", "Personal Development"],
  },
  {
    _id: "25",
    name: "Cycling Helmet",
    description: "Safety cycling helmet for protection during rides.",
    category: "Sports & Outdoors",
    tags: ["Cycling Helmet", "Cycling", "Safety"],
  },
  {
    _id: "26",
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker for wireless audio streaming.",
    category: "Electronics",
    tags: ["Bluetooth Speaker", "Audio", "Gadgets"],
  },
  {
    _id: "27",
    name: "Sweatpants",
    description: "Soft and comfortable sweatpants for lounging and exercise.",
    category: "Clothing",
    tags: ["Sweatpants", "Clothing", "Athleisure"],
  },
  {
    _id: "28",
    name: "Rice Cooker",
    description: "Automatic rice cooker for perfectly cooked rice every time.",
    category: "Home & Kitchen",
    tags: ["Rice Cooker", "Appliances", "Kitchen"],
  },
  {
    _id: "29",
    name: "Fantasy Novel",
    description:
      "Epic fantasy novel set in a mythical world of magic and adventure.",
    category: "Books",
    tags: ["Fantasy Novel", "Book", "Fantasy"],
  },
  {
    _id: "30",
    name: "Soccer Ball",
    description: "Official-size soccer ball for matches and practice sessions.",
    category: "Sports & Outdoors",
    tags: ["Soccer Ball", "Sports", "Soccer"],
  },
  // Add more products if needed
];
